package com.invincible.cryptotrader

object CryptoSymbol extends Enumeration {
  val Bitcoin = Value("btcusd")
  val ETHBTC = Value("ethbtc")
  val Ether = Value("ethusd")
  val Zcash = Value("zecusd")
  val ZECBTC = Value("zecbtc")
  val ZECETCH = Value("zeceth")
  val ZECBCH = Value("zecbch")
  val ZECLTC = Value("zecltc")
  val BitcoinCash = Value("bchusd")
  val BCHBTC = Value("bchbtc")
  val BCHETH = Value("bcheth")
  val Litecoin = Value("ltcusd")
  val LTCBTC = Value("ltcbtc")
  val LTCETH = Value("ltceth")
  val LTCBCH = Value("ltcbch")
  val BasicAttentionToken = Value("batusd")
  val Dai = Value("daiusd")
  val Chainlink = Value("linkusd")
  val Orchid = Value("oxtusd")
  val BATBTC = Value("batbtc")
  val LINKBTC = Value("linkbtc")
  val OXTBTC = Value("oxtbtc")
  val BATETH = Value("bateth")
  val LINKETCH = Value("linketh")
  val OTXTETH = Value("oxteth")
  val Amp = Value("ampusd")
  val Compound = Value("compusd")
  val PAXGold = Value("paxgusd")
  val Maker = Value("mkrusd")
  val Ox = Value("zrxusd")
  val KyberNetwork = Value("kncusd")
  val Decentraland = Value("manausd")
  val Storj = Value("storjusd")
  val Synthetix = Value("snxusd")
  val Curve = Value("crvusd")
  val Balancer = Value("balusd")
  val Uniswap = Value("uniusd")
  val Ren = Value("renusd")
  val Uma = Value("umausd")
  val Yearnfinance = Value("yfiusd")
  val BTCDAI = Value("btcdai")
  val ETHDAI = Value("ethdai")
  val AAVE = Value("aaveusd")
  val Filecoin = Value("filusd")
  val Skale = Value("sklusd")
  val GRTUSD = Value("grtusd")
  val BTCEUR = Value("btceur")
  val BTCGBP = Value("btcgbp")
  val ETHEUR = Value("etheur")
  val ETCGBP = Value("ethgbp")
  val BTCSGD = Value("btcsgd")
  val ETHSGD = Value("ethsgd")
  val BNTUSD = Value("bntusd")
  val OneINCH = Value("1inchusd")
  val ENJ = Value("enjusd")
  val Loopring = Value("lrcusd")
  val TheSandbox = Value("sandusd")
  val SomniumSpace = Value("cubeusd")
  val Livepeer = Value("lptusd")
  val Barnbridge = Value("bondusd")
  val Polygon = Value("maticusd")
  val InjectiveProtocol = Value("injusd")
  val Sushiswap = Value("sushiusd")
  val Dogecoin = Value("dogeusd")
  val AnkrNetwork = Value("ankrusd")
  val MirrorProtocol = Value("mirusd")
  val Alchemix = Value("alcxusd")
  val Fantom = Value("ftmusd")

  def toCryptoSymbol(s:String) = CryptoSymbol.values.find(_.toString == s)
}

import CryptoSymbol._

class CryptoCurrency(name:String, Ticker:String, symbol:CryptoSymbol.Value)
case class Bitcoin() extends CryptoCurrency("Bitcoin","BTC",CryptoSymbol.Bitcoin)
case class Ether() extends CryptoCurrency("Ether","ETH",CryptoSymbol.Ether)
